name: test-angular-mutation
inputs:
  folder:
    description: Working directory of Angular project
    required: true
permissions:
  contents: read
runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest

    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: latest
        cache: "pnpm"
        cache-dependency-path: ${{ inputs.folder }}/pnpm-lock.yaml

    - name: Install dependencies
      shell: bash
      run: pnpm install
      working-directory: ${{ inputs.folder }}

    - name: Mutation testing
      shell: bash
      run: pnpm exec stryker run
      working-directory: ${{ inputs.folder }}

    # TODO: Consider writing info to summary & badges.
    - name: Upload mutation test results
      uses: actions/upload-artifact@v4
      with:
        name: web-mutation-test-results
        path: ${{ inputs.folder }}/reports/mutation/mutation.html
